puts "The students of Villain Academy"
puts "----------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurser Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffery Baratheon"
puts "Norman Bates"